name: "Add warm-up problem"
description: "Submit a new practice problem."
title: "[Problem] "
labels: ["problem"]
body:
  - type: input
    id: title
    attributes:
      label: Problem title
      placeholder: "e.g., Reverse a string"
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      options:
        - Python
        - JavaScript
    validations:
      required: true